export const Regulamento = () => (
  <div className="flex flex-col gap-2 text-justify tracking-tighter">
    <p>
      <span className="font-bold">ARTIGO 01 – </span>O CAMPEONATO MUNICIPAL
      2023- OBJETIVO PROPORCIONAR MOMENTOS DE LAZER E BEM ESTAR PARA A
      COMUNIDADE EM GERAL, BEM COMO, ESTIMULAR A PRÁTICA E A ORGANIZAÇÃO
      ESPORTIVA NO MUNICÍPIO. ESTE LAZER É PROMOVIDO PELA PREFEITURA MUNICIPAL E
      SECRETARIA DE CULTURA, ESPORTE E JUVENTUDE. DAS INSCRIÇÕES
    </p>
    <p>
      <span className="font-bold">PARÁGRAFO 1º – </span>AS EQUIPES PODERÃO
      INSCREVER (04) QUATRO ATLETAS LINHAS E UM ATLETA NA EXCLUSIVIDADE DE
      GOLEIRO NO TOTAL DE 05 ATLETAS DE OUTRAS LOCALIDADES; CONSIDERA
      ESTRANGEIRO O ATLETA QUE NÃO TENHA VINCULO COM MUNICÍPIO: TÍTULO DE
      ELEITOR, RESIDIR, NATURALIDADE E EMPREGATÍCIO. OBS. NA CATEGORIA ABERTO,
      CASO EM O ATLETA SER MENOR DE IDADE A EQUIPE TERÁ A RESPONSABILIDADE TOTAL
      SOBRE O MESMO EM CASO DE ALGUMA EVENTUALIDADE VENHA OCORRER.
    </p>
    <p>
      <span className="font-bold">PARÁGRAFO 2º – </span>CADA EQUIPE PODERÁ NO
      DECORRER DA PARTIDA REALIZAR 05 (CINCO) SUBSTITUIÇÕES. NA CAT. DE BASE E
      NO VETERANO É VOLANTE
    </p>
    <p>
      <span className="font-bold">PARÁGRAFO 3º </span>O ATLETA QUE FOR INSCRITO
      EM UMA EQUIPE, NÃO PODERÁ IR PARA OUTRA EQUIPE, CASO SEJA LIBERADO, O
      REPRESENTANTE LEGAL TERÁ QUE COMUNICAR A SAÍDA DO ATLETA; ISSO SE AINDA
      NÃO TENHA ENTRADO EM CAMPO OU CITADO (CARTÕES...) EM SÚMULA, CASO NÃO
      OCORRA O MESMO FICARÁ LIBERADO, CASO CONTRÁRIO O ATLETA FICA
      IMPOSSIBILITADO DE PARTICIPAR EM OUTRA EQUIPE. OBS: MESMO O ATLETA
      INSCRITO NA SÚMULA ELE PODERÁ MUDAR PARA OUTRA EQUIPE, SALVO O
    </p>
    <p>
      <span className="font-bold">PARAGRAFO 3º </span>O ATLETA QUE ESTIVER
      INSCRITO NA COMPETIÇÃO OU NA SÚMULA PODERÁ ENTRAR A QUALQUER MOMENTO DA
      PARTIDA DE SUA EQUIPE.
    </p>
    <p>
      <span className="font-bold">ARTIGO 03 – </span>OS JOGOS SERÃO REALIZADOS
      NO ESTÁDIO MUNICIPAL NAS DATAS E HORÁRIOS CONFORME A TABELA. DATAS DOS
      JOGOS, PODERÃO EM CARÁTER EXCEPCIONAL, SEREM MODIFICADOS EM FUNÇÃO DE
      INTERESSES DA ORGANIZAÇÃO - DEPARTAMENTO DE ESPORTE E LAZER
      FARIASBRITENSE.
    </p>
    <p>
      <span className="font-bold">ARTIGO 04 – </span>NA HIPÓTESE DE UMA EQUIPE
      NÃO COMPARECER E SE CONCRETIZAR O W X O, ESTARÁ ELIMINADA DO CAMPEONATO
      POR DOIS ANOS. RESULTADO DA PARTIDA SERÁ POR 1 X 0 PARA O VENCEDOR; O
      MESMO ACONTECERÁ NAS PARTIDAS ANTERIORES...
    </p>
  </div>
);
