export const Regulamento = () => (
  <div className="flex flex-col gap-2 text-justify tracking-tighter">
    <p>
      <span className="font-bold">ARTIGO 1 – </span>O CAMPEONATO MUNICIPAL 2023
      – OBJETIVA PROPORCIONAR MOMENTOS DE LAZER E BEM ESTAR PARA A COMUNIDADE EM
      GERAL, BEM COMO, ESTIMULAR A PRÁTICA E A ORGANIZAÇÃO ESPORTIVA NO
      MUNICÍPIO. ESTE LAZER É PROMOVIDO PELA PREFEITURA MUNICIPAL E SECRETARIA
      DE CULTURA, ESPORTE E JUVENTUDE.
    </p>
    <span className="font-bold">
      DAS INSCRIÇÕES, DAS EQUIPES E DOS ATLETAS:
    </span>
    <p>
      <span className="font-bold">ARTIGO 2 – </span> AS EQUIPES PARTICIPANTES
      DEVERÃO INSCREVER NO MÍNIMO 15 (QUINZE) E NO MÁXIMO 25 (VINTE E CINCO)
      ATLETAS, AS INSCRIÇÕES SE ENCERRARÃO NO FINAL DA 2ª FASE. OBS: CASO O
      ATLETA SER MENOR DE IDADE, A EQUIPE TERÁ A RESPONSABILIDADE TOTAL SOBRE O
      MESMO EM CASO DE ALGUMA EVENTUALIDADE QUE VENHA OCORRER.
    </p>
    <p>
      <span className="font-bold">PARÁGRAFO 1º – </span>
      AS EQUIPES PODERÃO INSCREVER 04 (QUATRO) ATLETAS LINHAS E UM ATLETA NA
      EXCLUSIVIDADE DE GOLEITO, NO TOTAL DE 05 (CINCO) ATLETAS DE OUTRAS
      LOCALIDADES; CONSIDERA ESTRANGEIRO O ATLETA QUE NÃO TENHA VINCULO COM O
      MUNICÍPIO: TÍTULO DE ELEITOR, RESIDIR, NATURALIDADE E EMPREGATÍCIO...
    </p>
    <p>
      <span className="font-bold">PARÁGRAFO 2º: </span>CONSIDERA APTO A JOGAR
      COMO ATLETA DO MUNICÍPIO, OS ATLETAS QUE TIVEREM VINCULOS COM O MUNICÍPIO
      APRESENTANDO SEUS DOCUMENTOS COMPROBATÓRIOS TAIS COMO: RG OU CNH COM SUA
      NATURALIDADE DA CIDADE, TÍTULO DE ELEITOR, TÍTULO DE CIDADÃO, MORAR OU
      TRABALHAR COM DOCUMENTOS QUE COMPROVE E IDENTIFIQUE, ASSINADOS POR
      TESTEMUNHA...
    </p>
    <p>
      <span className="font-bold">PARÁGRAFO 3º: </span>O ATLETA QUE FOR INSCRITO
      EM UMA EQUIPE, NÃO PODERÁ IR PARA OUTRA EQUIPE, CASO SEJA LIBERADO, O
      REPRESENTANTE LEGAL TERÁ QUE COMUNICAR A SAÍDA DO ATLETA, ISSO SE AINDA
      NÃO TENHA ENTRADO EM CAMPO OU CITADO (CARTÕES...) EM SÚMULA, CASO NÃO
      OCORRA O MESMO FICARÁ LIBERADO, CASO CONTRÁRIO O ATLETA FICA
      IMPOSSIBILITADO DE PARTICIPAR EM OUTRA EQUIPE. OBS: MESMO O ATLETA
      INSCRITO NA SÚMULA ELE PODERÁ MUDAR PARA OUTRA EQUIPE, SALVO O PARAGRAFO
      3º. O ATLETA QUE ESTIVER INSCRITO NA COMPETIÇÃO OU NA SÚMULA PODERÁ ENTRAR
      A QUALQUER MOMENTO DA PARTIDA DE SUA EQUIPE.
    </p>
    <p>
      <span className="font-bold">ARTIGO 3 – </span> OS JOGOS SERÃO REALIZADOS
      NO ESTÁDIO MUNICIPAL NAS DATAS E HORÁRIOS CONFORME A TABELA. DATAS DOS
      JOGO, PODERÃO EM CARÁTER EXCEPCIONAL, SEREM MODIFICADAS EM FUNÇÃO DE
      INTERESSES DA ORGANIZAÇÃO – DEPARTAMENTO DE ESPORTE E LAZER
      FARIASBRITENSE.
    </p>
    <p>
      <span className="font-bold">ARTIGO 4 – </span>
      NA HIPÓTESE DE UMA EQUIPE NÃO COMPARECER E SE CONCRETIZAR O WXO ESTARÁ
      ELIMINADA DO CAMPEONATO POR DOIS ANOS. RESULTADO DA PARTIDA SERÁ POR 1 X 0
      PARA O VENCEDOR; O MESMO ACONTECERÁ NAS PARTIDAS ANTERIORES...
    </p>
    <p>
      <span className="font-bold">ARTIGO 5 – </span>SERÁ EXIGIDA DAS EQUIPES A
      PADRONIZAÇÃO DO UNIFORME (CAMISAS, CALÇÃO, MEIÃO E NÚMERO VÍSIVEL
      INDISPENSÁVEL NA CAMISA, EM CASO DE UNIFORMES SEMELHANTES A EQUIPE DO LADO
      DIREITO DA TABELA TROCARÁ O UNIFORME OU USARÁ COLETES CEDIDOS PELO
      DEPARTAMENTO.
    </p>
    <p>
      <span className="font-bold">ARTIGO 6 – </span>O ATLETA QUE FOR EXPULSO COM
      CARTÃO VERMELHO DE UMA PARTIDA ESTARÁ AUTOMATICAMENTE SUSPENSO PARA A
      SEGUINTE, E TERÁ SEU COMPORTAMENTO AVALIADO PELA COMISSÃO DISCIPLINAR... O
      ATLETA QUE FOR PUNIDO COM 02 (DOIS) CARTÕES AMARELOS FICARÁ SUSPENSO DA
      PARTIDA SEGUINTE, OS CARTÕES AMARELOS SÓ SERÃO ELIMINADOS PARA A FINAL.
      QUALQUER TENTATIVA OU AGRESSÃO FÍSICA A QUALQUER MEMBRO DA ORGANIZAÇÃO
      (MESÁRIO, ÁRBITROS, DIRETORIA E ETC.), O ATLETA SERÁ ELIMINADO DO
      CAMPEONATO...
    </p>
    <span className="font-bold">DA FORMA DE DISPUTA:</span>
    <p>
      <span className="font-bold">ARTIGO 7 – </span>A FORMULA DE DISPUTA SE
      ENCONTRA EXPOSTA NA TABELA. CADA PARTIDA SERÁ DISPUTADA EM 02 (DOIS)
      PERÍODOS DE 40 (QUARENTA) MINUTOS COM INTERVALO DE 10 (DEZ) MINUTOS, NA 1ª
      FASE E NA 2ª FASE CASO ACONTEÇA EMPATE NO TEMPO NORMAL AS EQUIPES IRÃO
      PARA DISPUTA DE PENÂLTI COM COBRANÇAS DE 03 PENÂLTIS, ONDE O VENCEDOR
      GANHARÁ PONTO EXTRA. AS PONTUAÇÕES DAS PARTIDAS: VITÓRIA 03 (TRÊS) PONTOS,
      EMPATE (VENCEDOR NOS PENÂLTIS) 02 (DOIS) PONTOS, EMPATE (PERDEDOR NOS
      PENALTIS) 01 (UM) PONTO. NAS QUARTAS, SEMIS E FINAL SERÃO PARTIDAS
      MATA-MATA, SAINDO EMPATE, PENÂLTI COM COBRANÇAS DE 05 (CINCO) PENÂLTIS.
      CADA EQUIPE PODERÁ, NO DECORRER DA PARTIDA, REALIZAR 05 (CINCO)
      SUBSTITUIÇÕES.
    </p>
    <span className="font-bold">
      DA POSSÍVEL FORMA DE DESEMPATE ENTRE DUAS OU MAIS EQUIPES NA 1ª E 2ª FASE,
      SEGUE O ARTIGO 08:
    </span>
    <p>
      <span className="font-bold"> ARTIGO 8 –</span>
      A- SALDO DE GOLS B- GOLS PRÓS (MARCADOS), C- GOLS CONTRA (SOFRIDOS), D-
      MENOR Nº DE CARTÕES AMARELOS.
    </p>
    <span className="font-bold">DAS DISPOSIÇÕES GERAIS:</span>
    <p>
      <span className="font-bold">ARTIGO 9 – </span>
      OS ASSUNTOS OMISSOS A ESTE REGULAMENTO SERÃO RESOLVIDOS
      ADMINISTRATIVAMENTE PELA COMISSÃO ORGANIZADORA E QUALQUER DÚVIDA QUE NÃO
      ESTIVER NESTE REGULAMENTO, PREVALECE A REGRA OFICIAL DE FUTEBOL.
    </p>
  </div>
);
